Drag n drop support
unkelhoebbi/semester-scheduler pull request #31
Opened 2022-02-23 16:21 UTC by Mafii

2022-02-23 16:25 UTC, jeremystucki commented
Can you add a screen recording to the PR?

2022-02-25 08:01 UTC, jeremystucki requested changes
Not working as intended

- Drag any module above another
- Both modules are now the same

2022-02-26 11:57 UTC, Mafii commented
> Not working as intended
> 
>     * Drag any module above another
> 
>     * Both modules are now the same

Fixed now, can you check again?

2022-02-26 12:46 UTC, jeremystucki approved these changes

2022-02-26 12:46 UTC, jeremystucki commented on src/components/Module.vue
> +        'background-color': this.$parent.$parent.$parent.getColorForCategory(module.categories[0])
So beautiful

2022-02-26 12:46 UTC, jeremystucki commented on src/components/Module.vue
> +      this.$parent.$parent.$parent.removeModule(this.semesterNumber, moduleId);
<3

2022-02-26 12:46 UTC, merged